### PR TITLE
final pull

### PR DESCRIPTION
**Pull request by khalidhammad402**

### CODE REVIEW

**Comment by Blastoise** [comment]
Follow the instructions about the folder structure and making a pull request.

**Comment by khalidhammad402** [comment]
Could you please explain how the structure of the repo should be?
And can i push the repo again?
As the deadline has crossed.

**Comment by khalidhammad402** [comment]
I made the required changes, please confirm.

**Comment by Blastoise** [comment]
You have Student-Hub folder a git-submodule. Delete the .git folder inside of Student-Hub to resolve.

**Comment by khalidhammad402** [comment]
I didn't have a .git folder inside but i did have a .gitignore file. I deleted it. Kindly check and respond.

**Pull request closed without merging**
