### PR TITLE
Team Noob

### PR DESCRIPTION
**Pull request by vishalsharma0657**
In S_CHAT folder, s_chat contains frontend code which is created in Flutter, schat_backend contains the backend code which is created in django.

### CODE REVIEW

**Comment by Blastoise** [comment]
schat_backend folder you pushed is a git submodule. Fix it. Probably removing .git folder inside schat_backend would fix the issue.

**Comment by Blastoise** [comment]
You deleted the License and README of the root folder.

**Comment by Blastoise** [comment]
Still not working.

**Comment by vishalsharma0657** [comment]
I have made a new pull request please check if it is fine

**Pull request closed without merging**
