### PR TITLE
Aimers Project Rozgar

### PR DESCRIPTION
**Pull request by Sid08JLUCKY**

### CODE REVIEW

**Comment by utkrisht3108** [comment]
Add Readme

**Comment by Blastoise** [comment]
@Sid08JLUCKY In the README.md there should be a section on **How to execute your code sample**

**Comment by Sid08JLUCKY** [comment]
Can you pls tell what should I include in it? Working of the wesite? Sent from Mail for Windows From: Ashutosh KumarSent: 09 January 2022 00:23To: ieeebitmesra/IEEE-MegaprojectCc: Sid08JLUCKY; MentionSubject: Re: [ieeebitmesra/IEEE-Megaproject] Aimers Project Rozgar (PR ***@***.*** In the README.md there should be a section on How to execute your code sample—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Blastoise** [comment]
@Sid08JLUCKY How will your application start?
.html page to open or anything.

**Pull request merged**
